package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
)

type AutoGenerated struct {
	Version string `json:"version"`
	ReqID   string `json:"reqId"`
	Status  string `json:"status"`
	Sig     string `json:"sig"`
	Table   struct {
		Cols []struct {
			ID    string `json:"id"`
			Label string `json:"label"`
			Type  string `json:"type"`
		} `json:"cols"`
		Rows []struct {
			C []struct {
				V string `json:"v"`
			} `json:"c"`
		} `json:"rows"`
	} `json:"table"`
}

func GetJson(address string) {
	googleUrl := "https://spreadsheets.google.com/tq?&tq=&key=" + address + "&gid=2"
	body, err := http.Get(googleUrl)
	if err != nil {
		log.Println(err)
	}
	defer body.Body.Close()

	content, err := ioutil.ReadAll(body.Body)
	if err != nil {
		log.Println(err)
	}

	var parsed AutoGenerated
	json.Unmarshal(content, &parsed)

	fmt.Printf("%+v", parsed.Table.Rows)
	fmt.Println("==================")

	for key, value := range parsed.Table.Rows {
		fmt.Println(key, value)
	}
	// fmt.Println("타입 :", reflect.TypeOf(parsed))

}

func main() {
	GetJson("116Ajw6c7JGGYY0pYBFAYh_tooM5SLC7yAtb4yUIp40Y")
}
